layout_spectrum: 0.2459942
typography_spectrum: 0.655907
color:
  saturation: 0.8094114
  lightness: 0.636646
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#E1C9A3'
    - '#8E5B00'
    - '#930000'
  rhythmicContrast: 0.2149423
name: A Life in the Life...Me!
